### ISSUE TITLE
Sending inputs through pnasnet error

### ISSUE THREAD

**Issue by mark-hoffmann** [Cadene/pretrained-models.pytorch#127]
I'm having a hard time using pnasnet5large. When I try to pass a test data input through the model I'm pulling it results in the error: `TypeError: forward() missing 1 required positional argument: 'x_right'`

Pytroch version: 1.0.0
pretrainedmodels version: 0.7.4

Example passthrough:
`model(batch[0].cuda())`

This is only the case for this particular network. For all other networks I have tried in this library, my test data input through works correctly. Is there something additional I need to do for my input data?

**Comment by mark-hoffmann** [comment]
I can try to take a stab at making a PR if you can clarify what you think the problem is.

From initial glance, my guess was it's a behavior that might have been allowed in Pytorch 0.4 but not in 1.0 in reference to using an ordered dict as the first layer of inputs in `Cell` class which implicitly may have passed the output through those two separate layers as the two required parameters in that `forward` method.

This is just a guess based on some digging I did on Pytorch forums. If that is what you think the issue is, a PR would be fairly straightforward.

**Comment by Cadene** [comment]
Thanks for reporting this issue.

What is your version of python?
We don't run tests for python2 at the moment.
Python3 should work with pytorch 0.4 and 1.0.

**Comment by mark-hoffmann** [comment]
I am using Python3.6 currently for this.

**Comment by mark-hoffmann** [comment]
It looks like the current tests aren't testing the cases of pnasnet5large or nasnet because of travis size limitations so this might have slipped through

**Comment by mark-hoffmann** [comment]
Ok, it looks like my first hypothesis was wrong. I'm trying to hunt this down, but am seeing some interesting behavior when debugging and was hoping you might have some ideas.

Looking at the `PNASNet5Large` class. In it's `forward` function we call both the `features` and the `logits`. I verified the correct number of parameters are being passed into each of the feature groups. When I started trying to debug, I tried commenting out the following lines in `forward` and going direct from input to the logits:

```
def forward(self, input):
        # x = self.features(input)
        # x = self.logits(x)
        x = self.logits(inputs)
        return x
```

What was interesting was even though we were bypassing the call to `features`, the `forward` method on `Cell` was still getting called. This was happening on instantiation of Cell objects. It wasn't until I commented out:

```
self.cell_stem_1 = Cell(in_channels_left=96, out_channels_left=108,
                                in_channels_right=270, out_channels_right=108,
                                match_prev_layer_dimensions=True,
                                is_reduction=True)
```

Through 

```
self.cell_11 = Cell(in_channels_left=4320, out_channels_left=864,
                            in_channels_right=4320, out_channels_right=864)
```

in the `PNASNet5Large` constructor that I was able to get stuff to not error out. 

Does this help give any more intuition @Cadene  as to the root of the problem? Or is there a detail that I'm just missing here?

**Comment by Cadene** [comment]
I just updated the tests. It works for me with torch 0.4 and torch 1.0.  Could you try to run this test and send me the result?
`pytest -v tests/test_pm_imagenet.py::test_pm_imagenet[pnasnet5large-imagenet]`

Your issue could be due to an incorrect shape. Please verify that the input of your net is of shape `(bsize x 3 x 331 x 331)`.
Thus, for a single image, it needs to be of shape `(1 x 3 x 331 x 331)`.

**Comment by mark-hoffmann** [comment]
Ok I finally got things to work. The test worked right away, but it seems that the problem was when trying to port into fastai. I was getting the error specified of `TypeError: forward() missing 1 required positional argument: 'x_right'` when data was trying to get passed through after removing the last couple of layers and wrapping in a `nn.Sequential`.

The problem is initially seen in the `create_cnn` function on the `create_body` line which looks like this and this respectively:
```
def create_cnn(data:DataBunch, arch:Callable, cut:Union[int,Callable]=None, pretrained:bool=True,
                lin_ftrs:Optional[Collection[int]]=None, ps:Floats=0.5,
                custom_head:Optional[nn.Module]=None, split_on:Optional[SplitFuncOrIdxList]=None,
                bn_final:bool=False, **kwargs:Any)->Learner:
    "Build convnet style learners."
    meta = cnn_config(arch)
    body = create_body(arch, pretrained, cut)
    nf = num_features_model(body) * 2
    head = custom_head or create_head(nf, data.c, lin_ftrs, ps=ps, bn_final=bn_final)
    model = nn.Sequential(body, head)
    learn = Learner(data, model, **kwargs)
    learn.split(ifnone(split_on,meta['split']))
    if pretrained: learn.freeze()
    apply_init(model[1], nn.init.kaiming_normal_)
    return learn
```

```
def create_body(arch:Callable, pretrained:bool=True, cut:Optional[int]=None, body_fn:Callable[[nn.Module],nn.Module]=None):
    "Cut off the body of a typically pretrained `model` at `cut` or as specified by `body_fn`."
    model = arch(pretrained)
    if not cut and not body_fn: cut = cnn_config(arch)['cut']
    return (nn.Sequential(*list(model.children())[:cut]) if cut
```

The problem seems to be coming from that return line. To get around this issue for the time being, I just went and substituted the last linear like you did in your codebase and then instantiated the fastai Learner object directly.:
```
def pnasnet5large(pretrained=False, output_classes=1):
    pretrained = 'imagenet' if pretrained else None
    model = pretrainedmodels.__dict__['pnasnet5large'](num_classes=1000, pretrained=pretrained)
    new_last_linear = nn.Linear(model.last_linear.in_features, output_classes)
    model.last_linear = new_last_linear
    return model

learn = Learner(data, pnasnet5large(pretrained=True, output_classes=1)
```

If you have any insight as to why wrapping in `nn.Sequential` was causing a problem I would be interested in understanding better.

**Comment by PPPW** [comment]
Hi @mark-hoffmann, yes, it's because of the `nn.Sequential` line in the `create_body` . `nn.Sequential` expects the modules to have exactly one argument in `forward`, but for PNASNet, a few layers, such as `CellStem1`, take two arguments in forward. 

We can't do in the usual way, we need to use the model as a whole then split it. I have a working [example here](https://github.com/PPPW/deep-learning-random-explore/blob/master/CNN_archs/cnn_archs.ipynb). I explained it in the NASNet section as they got the same issue. Hope it helps!

**Comment by mark-hoffmann** [comment]
Thank you for digging into this @PPPW this makes a lot of sense. I guess I missed in the documentation where `nn.Sequential` doesn't support layers that take 2 arguments in `foward`. 

I just assumed it would still work as normal because thinking about architectures like resnet we have residuals that are combined, however, looking further into those cases in code, they are implemented as being split and combined inside of the forward method that has a single argument as opposed to having the forward accept 2 arguments.

Much appreciated, makes sense!
